// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SonitCustom.DAL.Entities;

public partial class Product
{
    public string ProId { get; set; }

    public string ProName { get; set; }

    public string Description { get; set; }

    public string ImgUrl { get; set; }

    public string Price { get; set; }

    public int? Category { get; set; }

    public virtual Category CategoryNavigation { get; set; }
}