// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SonitCustom.DAL.Entities;

[Table("role")]
public partial class role
{
    [Key]
    public int roleId { get; set; }

    [Required]
    [StringLength(100)]
    public string roleName { get; set; }

    [InverseProperty("roleNavigation")]
    public virtual ICollection<user> users { get; set; } = new List<user>();
}